name: Build and validate PR (but don't deploy)
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: install deps
        run: npm ci
        shell: bash

      - name: create generated dir
        run: mkdir ./assets/generated
        shell: bash

      - name: create dependencies
        run: npm run generate:licenses; npm run generate:images; npm run generate:charging-stations; npm run generate:service-worker; npm run generate:editor-layer-index
        shell: bash

      - name: sync translations
        run: npm run generate:translations
        shell: bash

      - name: generate layeroverview
        run: npm run reset:layeroverview
        shell: bash

      - name: run tests
        run: npm run test
        shell: bash
